src/java/controlador/AgendaController.java
package controlador;

import entidad.Agenda;
import controlador.util.JsfUtil;
import controlador.util.JsfUtil.PersistAction;
import entidad.Lugares;
import sesion.AgendaFacade;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import org.primefaces.component.calendar.Calendar;

@ManagedBean(name = "agendaController", eager=true)
@ApplicationScoped
public class AgendaController implements Serializable {

    @EJB
    private sesion.AgendaFacade ejbFacade;
    private List<Agenda> items = null;
    private Agenda selected;
    private List<Agenda> items2 = null;
    private boolean isReunion = false;
    private boolean isEvento = false;
    private boolean isNnullx = false;
    private Agenda Eventos = null;
    
    public boolean isIsEvento() {
        isEvento = false;
        try {
            if ((selected.getTipo() == 1) && (selected.getIdAgenda() != -1)) {
                isEvento = true;
                isNnullx = true;
            }
        } catch (NullPointerException e) {
            isEvento = false;
            isNnullx = false;
        }
        return isEvento;
    }

    public void setIsEvento(boolean isEvento) {
        this.isEvento = isEvento;
    }

    public boolean isIsNnullx() {
        isNnullx = false;
        try {
            if ((selected.getIdAgenda() != -1)) {
                isNnullx = true;
            }
        } catch (NullPointerException e) {
            isReunion = false;
            isEvento = false;
            isNnullx = false;
        }

        return isNnullx;
    }

    public void setIsNnullx(boolean isNnullx) {
        this.isNnullx = isNnullx;
    }

    public boolean isIsReunion() {
        isReunion = false;
        try {
            if ((selected.getTipo() == 0) && (selected.getIdAgenda() != -1)) {
                isReunion = true;
                isNnullx = true;
            }
        } catch (NullPointerException e) {
            isReunion = false;
            isNnullx = false;
        }
        return isReunion;
    }

    public void setIsReunion(boolean isReunion) {
        this.isReunion = isReunion;
    }

    public AgendaController() {
    }

    public Agenda getSelected() {
        return selected;
    }

    public void setSelected(Agenda selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    public List<Agenda> findByFechaAndLugar(Calendar x, Lugares idLugares) {
        Date fecha = (Date) x.getValue();
        return getFacade().findByFechaAndLugar(fecha, idLugares);
    }

    protected void initializeEmbeddableKey() {
    }

    private AgendaFacade getFacade() {
        return ejbFacade;
    }

    public Agenda prepareCreate() {
        selected = new Agenda();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        if (selected.getTipo() == 1) {
            Date temp = addDaysToDate(selected.getFechaIncioReg(),2);
            selected.setFechaFinReg(temp);
        }
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/agenda3").getString("AgendaCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        if (selected.getTipo() == 1) {
            Date temp = addDaysToDate(selected.getFechaIncioReg(),2);
            selected.setFechaFinReg(temp);
        }
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/agenda3").getString("AgendaUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/agenda3").getString("AgendaDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Agenda> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    public List<Agenda> getItems2() {

        Date fecha = new Date ();
        Date consulta=new Date();
        
        int dia=fecha.getDay();
       int numero=0;
        switch(dia)
        {
            case 0:
                numero=8;
                break;
            case 1:
                numero=7;
                break;
            case 2:
                numero=6;
                break;
            case 3:
                numero=5;
                break;
            case 4:
                numero=4;
                break;
            case 5:
                numero=3;
                break;
            case 6:
                numero=2;
                break;                
            
        }
                
        if (items2 == null) {
            consulta=addDaysToDate(fecha,numero);
            items2 = getFacade().findByIndex(consulta);
        }

        return items2;
    }

    
    public List<Agenda> findByReunionEmp(int idEmpleados) {
        return getFacade().findByReunionEmp(idEmpleados);
    }

    public List<Agenda> findByReunionProv(int idProveedores) {
        return getFacade().findByReunionProv(idProveedores);
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/agenda3").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/agenda3").getString("PersistenceErrorOccured"));
            }
        }
    }

    public List<Agenda> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Agenda> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Agenda.class)
    public static class AgendaControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AgendaController controller = (AgendaController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "agendaController");
            return controller.getFacade().find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Agenda) {
                Agenda o = (Agenda) object;
                return getStringKey(o.getIdAgenda());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Agenda.class.getName()});
                return null;
            }
        }

    }

    public static Date addDaysToDate(Date date, int x) {
        java.util.Calendar calendarDate = java.util.Calendar.getInstance();
        calendarDate.setTime(date);
        calendarDate.add(java.util.Calendar.DAY_OF_YEAR, x);
        return calendarDate.getTime();
    }

}

web/Bienvenidos1.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Agenda Colaborativa</title>
            </f:facet>
        </h:head>

        <h:body>
        <!--ui:composition template="templates/busqueda.xhtml"-->
            <p:layout fullPage="true">

                  <p:layoutUnit position="north" size="100">
                    <p:graphicImage  library="img" name="agenda.jpg"/>
                </p:layoutUnit>

                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    
                    <p align="right"> <b>Cerrar Sesion</b></p>
                </p:layoutUnit>
               <p:layoutUnit position="center" resizable="true"  >                   
                   <div align="center">
                       <p align="right">Sesion:</p>
                    <h:form>
                        <p:dataTable  var="agendados" paginator="true" >
                        <f:facet name="caption">Reuniones Agendadas</f:facet>
                        <p:column>
                                <f:facet name="header">
                                    TIPO
                                </f:facet>
                            </p:column>
                        <p:column>
                                <f:facet name="header">
                                    AREA
                                </f:facet>
                            </p:column>
                        <p:column>
                                <f:facet name="header">
                                    NOMBRE DEL AREA
                                </f:facet>
                            </p:column>
                        <p:column>
                                <f:facet name="header">
                                    FECHA
                                </f:facet>
                            </p:column>
                        <p:column>
                                <f:facet name="header">
                                    HORA
                                </f:facet>
                            </p:column>
                        <p:column>
                                <f:facet name="header">
                                    LISTADO DE PARTICIPANTES
                                </f:facet>
                            </p:column>
                        </p:dataTable>
                    </h:form>
                </div>     
                </p:layoutUnit>

            </p:layout>
            <!--/ui:composition-->
        </h:body>

    </f:view>
</html>

web/Createl.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="LugaresCreateDlg" widgetVar="LugaresCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{agenda3.CreateLugaresTitle}">
            <h:form id="LugaresCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{lugaresController.selected != null}">
                        <p:outputLabel value="#{agenda3.CreateLugaresLabel_idLugares}" for="idLugares" />
                        <p:inputText id="idLugares" value="#{lugaresController.selected.idLugares}" title="#{agenda3.CreateLugaresTitle_idLugares}" required="true" requiredMessage="#{agenda3.CreateLugaresRequiredMessage_idLugares}"/>
                        <p:outputLabel value="#{agenda3.CreateLugaresLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{lugaresController.selected.nombre}" title="#{agenda3.CreateLugaresTitle_nombre}" required="true" requiredMessage="#{agenda3.CreateLugaresRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{agenda3.CreateLugaresLabel_capcidad}" for="capcidad" />
                        <p:inputText id="capcidad" value="#{lugaresController.selected.capcidad}" title="#{agenda3.CreateLugaresTitle_capcidad}" required="true" requiredMessage="#{agenda3.CreateLugaresRequiredMessage_capcidad}"/>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{lugaresController.create}" value="#{agenda3.Save}" update="display,:LugaresListForm:datalist,:growl" oncomplete="handleSubmit(args,'LugaresCreateDialog');"/>
                    <p:commandButton value="#{agenda3.Cancel}" onclick="LugaresCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/Edite.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="EmpleadosEditDlg" widgetVar="EmpleadosEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{agenda.EditEmpleadosTitle}">
            <h:form id="EmpleadosEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{empleadosController.selected != null}">
                        <p:outputLabel value="#{agenda.EditEmpleadosLabel_idEmpleados}" for="idEmpleados" />
                        <p:inputText id="idEmpleados" value="#{empleadosController.selected.idEmpleados}" title="#{agenda.EditEmpleadosTitle_idEmpleados}" required="true" requiredMessage="#{agenda.EditEmpleadosRequiredMessage_idEmpleados}"/>
                        <p:outputLabel value="#{agenda.EditEmpleadosLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{empleadosController.selected.nombre}" title="#{agenda.EditEmpleadosTitle_nombre}" required="true" requiredMessage="#{agenda.EditEmpleadosRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{agenda.EditEmpleadosLabel_apellido}" for="apellido" />
                        <p:inputText id="apellido" value="#{empleadosController.selected.apellido}" title="#{agenda.EditEmpleadosTitle_apellido}" required="true" requiredMessage="#{agenda.EditEmpleadosRequiredMessage_apellido}"/>
                        <p:outputLabel value="#{agenda.EditEmpleadosLabel_emailP}" for="emailP" />
                        <p:inputText id="emailP" value="#{empleadosController.selected.emailP}" title="#{agenda.EditEmpleadosTitle_emailP}" required="true" requiredMessage="#{agenda.EditEmpleadosRequiredMessage_emailP}"/>
                        <p:outputLabel value="#{agenda.EditEmpleadosLabel_emailE}" for="emailE" />
                        <p:inputText id="emailE" value="#{empleadosController.selected.emailE}" title="#{agenda.EditEmpleadosTitle_emailE}" required="true" requiredMessage="#{agenda.EditEmpleadosRequiredMessage_emailE}"/>
                        <p:outputLabel value="#{agenda.EditEmpleadosLabel_telefono}" for="telefono" />
                        <p:inputText id="telefono" value="#{empleadosController.selected.telefono}" title="#{agenda.EditEmpleadosTitle_telefono}" required="true" requiredMessage="#{agenda.EditEmpleadosRequiredMessage_telefono}"/>
                        <p:outputLabel value="#{agenda.EditEmpleadosLabel_nss}" for="nss" />
                        <p:inputText id="nss" value="#{empleadosController.selected.nss}" title="#{agenda.EditEmpleadosTitle_nss}" required="true" requiredMessage="#{agenda.EditEmpleadosRequiredMessage_nss}"/>
                        <p:outputLabel value="#{agenda.EditEmpleadosLabel_idUsers}" for="idUsers" />
                        <p:selectOneMenu id="idUsers" value="#{empleadosController.selected.idUsers}" required="true" requiredMessage="#{agenda.EditEmpleadosRequiredMessage_idUsers}">
                            <f:selectItem itemLabel="#{agenda.SelectOneMessage}"/>
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idUsersItem"
                                           itemValue="#{idUsersItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{empleadosController.update}" value="#{agenda.Save}" update="display,:EmpleadosListForm:datalist,:growl" oncomplete="handleSubmit(args, 'EmpleadosEditDialog');"/>
                    
                    <p:commandButton value="#{agenda.Cancel}" onclick="EmpleadosEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/SalidaBusqueda.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Agenda Colaborativa</title>
            </f:facet>
        </h:head>

        <h:body>
        
            <p:layout fullPage="true">

                 <p:layoutUnit position="north" size="100">
                    <p:graphicImage  library="img" name="agenda.jpg"/>
                </p:layoutUnit>

                <p:layoutUnit position="west" resizable="true" closable="true" collapsible="true">
                    <p:layout fullPage="true">
                <h:form>
                    <p:growl id="messages" showDetail="true"/>
                    <label>Busqueda</label>
                    <p:slideMenu>                                                                     
                        <p:submenu label="Reunion">
                            <p:submenu label="Fecha">
                                <p:menuitem>
                                    <p:calendar/>
                                </p:menuitem>
                                <p:menuitem>
                                    <p:button value=" Buscar"/>
                                </p:menuitem>
                            </p:submenu>                            
                            <p:submenu label="Nombre"><p:menuitem><p:inputText placeholder="Nombre"/></p:menuitem><p:menuitem><p:button value=" Buscar"/></p:menuitem></p:submenu>
                            <p:submenu label="Lugar"><p:menuitem><p:inputText placeholder="Lugar"/></p:menuitem><p:menuitem><p:button value=" Buscar"/></p:menuitem></p:submenu>
                        </p:submenu>
                        <p:submenu label="Evento">
                            <p:submenu label="Fecha"><p:menuitem><p:calendar/></p:menuitem><p:menuitem><p:button value=" Buscar"/></p:menuitem></p:submenu>
                            <p:submenu label="Nombre"><p:menuitem><p:inputText placeholder="Nombre"/></p:menuitem><p:menuitem><p:button value=" Buscar"/></p:menuitem></p:submenu>
                            <p:submenu label="Lugar"><p:menuitem><p:inputText placeholder="Lugar"/></p:menuitem><p:menuitem><p:button value=" Buscar"/></p:menuitem></p:submenu>
                        </p:submenu>                      
                        <p:submenu label="Fecha">
                                <p:menuitem>
                                    <p:calendar/>
                                </p:menuitem>
                                <p:menuitem>
                                    <p:button value=" Buscar"/>
                                </p:menuitem>
                            </p:submenu>                            
                    </p:slideMenu>
                </h:form>
            </p:layout>
                    
                </p:layoutUnit>
                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    
                </p:layoutUnit>
                
               <p:layoutUnit position="center" resizable="true"  >     
                   
                   <div align="center">
                    <h:form>
                        
                        <p:dataTable value="#{agendaController.items}" selection="#{agendaController.selected}" rowKey="#{ag.idAgenda}"  var="agendados" paginator="true" >
                        <f:facet name="caption">Reuniones Agendadas</f:facet>
                        <p:column headerText="TIPO">
                            #{agendados.tipo}
                            </p:column>
                        <p:column headerText="AREA">
                            #{agendados.area}
                            </p:column>
                        <p:column headerText="NOMBRE DE LA REUNION">
                            #{agendados.nombre}
                            </p:column>
                        <p:column headerText="FECHA (DIA/MES)">
                            #{agendados.fecha.day}/#{agendados.fecha.month}
                            </p:column>
                        <p:column headerText="HORA">
                            #{agendados.hora.hours}:#{agendados.hora.minutes}:#{agendados.hora.seconds}
                            </p:column>
                        <p:column>
                                <f:facet name="header">
                                    LISTADO DE PARTICIPANTES
                                </f:facet>
                            #{agendados.participantes}
                            </p:column>
                        </p:dataTable>
                    </h:form>
                </div>     
                </p:layoutUnit>

            </p:layout>
        </h:body>

    </f:view>
</html>

web/editar_empleado.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/templateAgenda.xhtml">

        <ui:define name="title">
        </ui:define>

        <ui:define name="headerX">
            <p:graphicImage  library="img" name="agenda.jpg"/>

        </ui:define>

        <ui:define name="leftSideBar">
            <p:layoutUnit position="west" size="175" header="Menú" collapsible="true">
                <p:menu>
                    <p:menuitem value="Cerrar Sesion" outcome="index" /> 
                    <p:submenu label="Edición" >                   
                        <p:menuitem value="Incio" outcome="vista_Administrador" />
                        <p:menuitem value="Empleados" outcome="/editar_empleado" />
                        <p:menuitem value="Provedores" outcome="/editar_proveedor"  />
                        <p:menuitem value="Lugares" outcome="editar_lugares" />
                    </p:submenu>
                </p:menu>
            </p:layoutUnit>
        </ui:define>

        <ui:define name="body">
            <h:form id="EmpleadosListForm">
                <p:panel header="Editar Empleados">
                    <p:dataTable id="datalist" value="#{empleadosController.items}" var="item"
                                 selectionMode="single" selection="#{empleadosController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idEmpleados}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListEmpleadosTitle_idEmpleados}"/>
                            </f:facet>
                            <h:outputText value="#{item.idEmpleados}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListEmpleadosTitle_nombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListEmpleadosTitle_apellido}"/>
                            </f:facet>
                            <h:outputText value="#{item.apellido}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListEmpleadosTitle_emailP}"/>
                            </f:facet>
                            <h:outputText value="#{item.emailP}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListEmpleadosTitle_emailE}"/>
                            </f:facet>
                            <h:outputText value="#{item.emailE}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListEmpleadosTitle_telefono}"/>
                            </f:facet>
                            <h:outputText value="#{item.telefono}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListEmpleadosTitle_nss}"/>
                            </f:facet>
                            <h:outputText value="#{item.nss}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{agenda.ListEmpleadosTitle_idUsers}"/>
                            </f:facet>
                            <h:outputText value="#{item.idUsers}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{agenda.Create}" actionListener="#{empleadosController.prepareCreate}" update=":EmpleadosCreateForm" oncomplete="PF('EmpleadosCreateDialog').show()"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{agenda.Edit}" update=":EmpleadosEditForm" oncomplete="PF('EmpleadosEditDialog').show()" disabled="#{empty empleadosController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{agenda.Delete}" actionListener="#{empleadosController.destroy}" update=":growl,datalist" disabled="#{empty empleadosController.selected}"/>

                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Edite.xhtml"/>
            <ui:include src="Createe.xhtml"/>

        </ui:define>
    </ui:composition>

</html>

web/templateAgenda.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title><ui:insert name="title">Agenda Colaborativa</ui:insert></title>
        <h:outputStylesheet library="css" name="jsfcrud.css"/>
        <h:outputScript library="js" name="jsfcrud.js"/>
        <h:outputScript library="primefaces" name="jquery/jquery.js"/>
    </h:head>

    <h:body>

        <p:growl id="growl" life="3000" />

        <p:layout fullPage="true">
            <p:layoutUnit position="north"  size="100">
                <ui:insert name="headerX"/>
            </p:layoutUnit>

            <p:layoutUnit position="center">
                <ui:insert name="body"/>
            </p:layoutUnit>

            <ui:insert name="leftSideBar"/>


        </p:layout>

    </h:body>

</html>

web/verParticipantes.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="VerConfDlg" widgetVar="VerConfDialog" modal="true" resizable="false" appendTo="@(body)" header="confirmados al evento">
            <h:form id="VerConfForm">
                <h:panelGroup id="display">
                    <p:panelGrid  rendered="#{agendaController.selected != null}" >
                        <p:dataList value="#{eventoparticipantesController.getItems4(agendaController.selected)}" var="emp" type="ordered">
                            #{emp.idAutoRegistro.nombre}   #{emp.idAutoRegistro.apellido} #{emp.idAutoRegistro.empresa}                        
                        </p:dataList>
                    </p:panelGrid>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>